# Generated by Django 5.1.8 on 2025-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the guide is available for booking during this time'),
        ),
    ]
